version: "3.8"
services:
    os:
        image: amazonlinux

    nginx:
        container_name: nginx
        depends_on:
            - app
        ports:
            - "443:443"
            - "80:80"
        volumes:
            # Logging
            - ./nginx/log:/var/log/nginx/
            # Volume đến code ứng dụng
            - .:/var/www/html
            # config for ssl if need
            - ./nginx/conf.d/laravel.conf:/etc/nginx/conf.d/default.conf
            - ./letsencrypt:/etc/letsencrypt
        build:
            context: ./nginx
            network: host
            args:
                - CERTBOT_EMAIL=buiquangloi1993@gmail.com #replace with your own email
                - DOMAIN_LIST=luatatlantic.com
        working_dir: /var/www/html
        restart: unless-stopped
        networks:
            - app-network

    mysql:
        image: mariadb
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: 'laravel'
            MYSQL_USER: 'admin'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'

    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: bitnami/laravel
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - app-network

    redis:
        image: redis:3.2

    certbot:
        image: certbot/certbot
        container_name: certbot
        depends_on:
            - nginx
        command: certonly --webroot --webroot-path=/var/www/html --email buiquangloi1993@gmail.com --agree-tos --no-eff-email --force-renewal -d luatatlantic.com

networks:
    app-network:
        driver: bridge
